<?php

/**
 * @file
 * Islandora pdf solution pack module
 */

/**
 * islandora pdf sp required fedora objects
 * @return type 
 */
function islandora_pdf_sp_required_fedora_objects() {

    // Get the module path
    $module_path = drupal_get_path('module', 'islandora_pdf_sp');

    return array(
    'islandora_pdf_sp' => array(
      'module' => 'islandora_pdf_sp',
      'title' => 'Islandora PDF Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_strict_pdf',
          'label' => 'Islandora strict PDF content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/STRICT_SP_PDFCM.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'islandora:sp_pdf_collection',
          'label' => 'Islandora PDF Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/PDF-COLLECTION POLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * SP Hook: Set the solution pack defaults 
 * @param type $data
 * @return string 
 */
function islandora_pdf_sp_setup_defaults(&$data)
{
    // Get the module path
    $module_path = drupal_get_path('module', 'islandora_pdf_sp');
    
    // Create an area for this solution pack
    $data['islandora_pdf_sp'] = array(
        'label' => 'Islandora PDF Solution Pack',
        'forms' => array(
            array(
                'label' => 'Islandora PDF Solution Pack',
                'file' => "$module_path/mods_article.xml",
            ),
        ), 
        'objects' => array(
            array(
                'pid' => 'islandora:sp_strict_pdf',
                'label' => 'Islandora strict PDF content model',
                'dsid' => 'ISLANDORACM',
                'datastream_file' => "$module_path/xml/STRICT_SP_PDFCM.xml",
                'dsversion' => NULL,
                'foxml_file' => NULL,
                'form' => 'Islandora PDF Solution Pack'
            ), 
            array(
                'pid' => 'islandora:sp_pdf_collection',
                'label' => 'Islandora PDF Collection',
                'cmodel' => 'islandora:collectionCModel',
                'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
                'datastreams' => array(
                    array(
                        'dsid' => 'TN',
                        'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
                        'mimetype' => 'image/png',
                    ),
                    array(
                        'dsid' => 'COLLECTION_POLICY',
                        'datastream_file' => "$module_path/xml/PDF-COLLECTION POLICY.xml",
                    )
                )
            )
        )
    );
    
    // Return the config
    return $data;
}
